import { NAMES_EDITORIAL } from "../../default/editoriales.default";
import { LibroDefaultProp } from "../interface/libro.interface";
import { NAMES_MATERIAS } from "../../materia/default/materia.default";
import { NAMES_COMPONENTE } from "../../componente/default/componente.default";
import { Especificaciones } from "../../libro_pedido/interface/especificaciones.interface";
import { NAMES_LIBRO } from "./libro_name.default";

export const LIBRO_LEARN: LibroDefaultProp[] = [
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '1',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/0yf3Xk2/5bc27646f69b.png',
    cantidadPg: 100,
    adhesivos: 4,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '1',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/kJMSTSn/4574a4fbc61c.png',
    cantidadPg: 59,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '2',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/kc09NvV/d43eb6cc495b.png',
    cantidadPg: 96,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '2',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/30xrVJJ/48eed15ebc3f.png',
    cantidadPg: 59,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '3',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/q3qw1ZG0/ff1b7ac9e5e3.png',
    cantidadPg: 76,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '3',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/svYRyGZn/5e7b3fc94e0f.png',
    cantidadPg: 99,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '3',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/N61cDC1Y/b7ec8b8582b0.png',
    cantidadPg: 38,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ENTRY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '4',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/Hf2fDDYy/83ca6ee4b401.png',
    cantidadPg: 76,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '4',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/ZZPp3vq/4f041b3097ea.png',
    cantidadPg: 99,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '5',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/RpxVDQPN/410d40df0d1b.png',
    cantidadPg: 85,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '5',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/cXXrdR9D/68c05be9183b.png',
    cantidadPg: 99,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '6',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/VcT9CNgH/ff8fa562ea7b.png',
    cantidadPg: 92,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '6',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'hhttps://i.ibb.co/Q76fNyQk/04c15dfcf564.png',
    cantidadPg: 113,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  }
];

export const LIBRO_LEARN_NOW: LibroDefaultProp[] = [

  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '1',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 108,
    adhesivos: 4,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.STUDENT],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '1',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 64,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 2,
    nivel: '2',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 104,
    adhesivos: 4,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '2',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 67,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '3',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 108,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '3',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 106,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '4',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 80,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '4',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 96,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '5',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 80,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '5',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 96,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '6',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 88,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '6',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 96,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
]

export const LIBRO_BRIGHT: LibroDefaultProp[] = [
  {
    nombre: NAMES_LIBRO.BRIGHT,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: 'starter',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2018',
    img: 'https://i.ibb.co/M5yMb97R/3cf1cdf92b14.png',
    cantidadPg: 76,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHT,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: 'starter',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2018',
    img: 'https://i.ibb.co/wZZDSWFs/25d0fdb45fdf.png',
    cantidadPg: 72,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHT,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '1',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2018',
    img: 'https://i.ibb.co/7yn3wP6/45d311784960.png',
    cantidadPg: 113,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHT,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '1',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2018',
    img: 'https://i.ibb.co/ySFD5v6/1695387655b3.png',
    cantidadPg: 122,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHT,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '2',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2018',
    img: 'https://i.ibb.co/PN8gyMp/b5e41b7c4ef3.png',
    cantidadPg: 113,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHT,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '2',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2018',
    img: 'https://i.ibb.co/PN8gyMp/b5e41b7c4ef3.png',
    cantidadPg: 122,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHT,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '3',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2018',
    img: 'https://i.ibb.co/JQCDq9m/0aa34668c531.png',
    cantidadPg: 112,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHT,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '3',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2018',
    img: 'https://i.ibb.co/cxt3mLk/7dee84cd8325.png',
    cantidadPg: 121,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHT,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '4',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2018',
    img: '',
    cantidadPg: 121,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHT,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '4',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2018',
    img: '',
    cantidadPg: 121,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHT,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '5',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2018',
    img: 'https://i.ibb.co/qFRZ8L5/02e465c19515.png',
    cantidadPg: 113,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHT,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '5',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2018',
    img: 'https://i.ibb.co/P1dvF57/a129e90ddbfb.png',
    cantidadPg: 122,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHT,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '6',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2018',
    img: '',
    cantidadPg: 120,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHT,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '6',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2018',
    img: '',
    cantidadPg: 128,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  }
];

export const LIBRO_BRIGHTER: LibroDefaultProp[] = [
  {
    nombre: NAMES_LIBRO.BRIGHTER,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: 'starter',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2024',
    img: 'https://i.ibb.co/Kc2DNmmZ/0640d100dc4f.png',
    cantidadPg: 116,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHTER,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: 'starter',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2024',
    img: 'https://i.ibb.co/PzZhRTDr/ecc3587589f9.png',
    cantidadPg: 72,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHTER,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '1',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2024',
    img: 'https://i.ibb.co/PWhLzpT/aafc046630ed.png',
    cantidadPg: 116,
    adhesivos: 4,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHTER,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '1',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2024',
    img: 'https://i.ibb.co/ySFD5v6/1695387655b3.png',
    cantidadPg: 127,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHTER,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '2',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2024',
    img: 'https://i.ibb.co/bgF53Pjw/c67ff703bd52.png',
    cantidadPg: 116,
    adhesivos: 4,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHTER,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '2',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2024',
    img: 'https://i.ibb.co/v6mSFTXH/9457cd6d43ea.png',
    cantidadPg: 104,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHTER,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '3',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2024',
    img: 'https://i.ibb.co/2jJZktL/e1f2a281d346.png',
    cantidadPg: 116,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHTER,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '3',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2024',
    img: 'https://i.ibb.co/0s9BV4t/4f386f5083f8.png',
    cantidadPg: 132,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHTER,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '4',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2024',
    img: 'https://i.ibb.co/L5HCVGV/c8b2b0108375.png',
    cantidadPg: 120,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHTER,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '4',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2024',
    img: 'https://i.ibb.co/ZTfTVD2/9cee2fde15aa.png',
    cantidadPg: 96,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHTER,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '5',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2024',
    img: 'https://i.ibb.co/qyyNxYL/e75daf7c5a2d.png',
    cantidadPg: 115,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHTER,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '5',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2024',
    img: 'https://i.ibb.co/4ZjHz16/4e6ae90f6354.png',
    cantidadPg: 131,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHTER,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '6',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2024',
    img: '',
    cantidadPg: 114,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.BRIGHTER,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '6',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2024',
    img: '',
    cantidadPg: 131,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  }
];