import { NAMES_EDITORIAL } from "@src/default/editoriales.default";
import { LibroDefaultProp } from "../interface/libro.interface";
import { NAMES_MATERIAS } from "@src/materia/default/materia.default";
import { NAMES_COMPONENTE } from "@src/componente/default/componente.default";
import { Especificaciones } from "@src/libro_pedido/interface/especificaciones.interface";

export const NAMES_LIBRO = {
  LEARN: 'Learn whit us',
  LEARN_NOW: 'Learn whit us NOW'
} as const;

export const LIBRO_DEFAULT: LibroDefaultProp[] = [
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '1',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/0yf3Xk2/5bc27646f69b.png',
    cantidadPg: 100,
    adhesivos: 4,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '1',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/kJMSTSn/4574a4fbc61c.png',
    cantidadPg: 59,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '2',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/kc09NvV/d43eb6cc495b.png',
    cantidadPg: 96,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '2',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/30xrVJJ/48eed15ebc3f.png',
    cantidadPg: 59,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '3',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/q3qw1ZG0/ff1b7ac9e5e3.png',
    cantidadPg: 76,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '3',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/svYRyGZn/5e7b3fc94e0f.png',
    cantidadPg: 99,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '3',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/N61cDC1Y/b7ec8b8582b0.png',
    cantidadPg: 38,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ENTRY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '4',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/Hf2fDDYy/83ca6ee4b401.png',
    cantidadPg: 76,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '4',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/ZZPp3vq/4f041b3097ea.png',
    cantidadPg: 99,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '5',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/RpxVDQPN/410d40df0d1b.png',
    cantidadPg: 85,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '5',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/cXXrdR9D/68c05be9183b.png',
    cantidadPg: 99,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '6',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'https://i.ibb.co/VcT9CNgH/ff8fa562ea7b.png',
    cantidadPg: 92,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '6',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2019',
    img: 'hhttps://i.ibb.co/Q76fNyQk/04c15dfcf564.png',
    cantidadPg: 113,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '1',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 108,
    adhesivos: 4,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.STUDENT],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '1',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 64,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 2,
    nivel: '2',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 104,
    adhesivos: 4,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '2',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 67,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '3',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 108,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '3',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 106,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '4',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 80,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '4',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 96,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '5',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 80,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '5',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 96,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '6',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 88,
    adhesivos: 2,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.CLASS],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
  {
    nombre: NAMES_LIBRO.LEARN_NOW,
    descripcion: 'Libro de ingles',
    edicion: 1,
    nivel: '6',
    editorial: NAMES_EDITORIAL.OXFORD,
    anio: '2025',
    img: '',
    cantidadPg: 96,
    adhesivos: 0,
    materia: NAMES_MATERIAS.INGLES,
    componentes: [NAMES_COMPONENTE.ACTIVITY],
    especificacionesDefecto: [Especificaciones.COLOR, Especificaciones.DOBLE_FAZ, Especificaciones.ANILLADO]
  },
]