import { LIBRO_BRIGHT, LIBRO_BRIGHTER, LIBRO_LEARN, LIBRO_LEARN_NOW } from "./libro_biblioteca-default";

export const NAMES_LIBRO_EXT = {
  LEARN_1_CB: `${LIBRO_LEARN[0].nombre} - ${LIBRO_LEARN[0].nivel} - ${LIBRO_LEARN[0]?.componentes?.join(' - ')}`,
  LEARN_1_AB: `${LIBRO_LEARN[1].nombre} - ${LIBRO_LEARN[1].nivel} - ${LIBRO_LEARN[1]?.componentes?.join(' - ')}`,
  LEARN_2_CB: `${LIBRO_LEARN[2].nombre} - ${LIBRO_LEARN[2].nivel} - ${LIBRO_LEARN[2]?.componentes?.join(' - ')}`,
  LEARN_2_AB: `${LIBRO_LEARN[3].nombre} - ${LIBRO_LEARN[3].nivel} - ${LIBRO_LEARN[3]?.componentes?.join(' - ')}`,
  LEARN_3_CB: `${LIBRO_LEARN[4].nombre} - ${LIBRO_LEARN[4].nivel} - ${LIBRO_LEARN[4]?.componentes?.join(' - ')}`,
  LEARN_3_AB: `${LIBRO_LEARN[5].nombre} - ${LIBRO_LEARN[5].nivel} - ${LIBRO_LEARN[5]?.componentes?.join(' - ')}`,
  LEARN_3_EB: `${LIBRO_LEARN[6].nombre} - ${LIBRO_LEARN[6].nivel} - ${LIBRO_LEARN[6]?.componentes?.join(' - ')}`,
  LEARN_4_CB: `${LIBRO_LEARN[7].nombre} - ${LIBRO_LEARN[7].nivel} - ${LIBRO_LEARN[7]?.componentes?.join(' - ')}`,
  LEARN_4_AB: `${LIBRO_LEARN[8].nombre} - ${LIBRO_LEARN[8].nivel} - ${LIBRO_LEARN[8]?.componentes?.join(' - ')}`,
  LEARN_5_CB: `${LIBRO_LEARN[9].nombre} - ${LIBRO_LEARN[9].nivel} - ${LIBRO_LEARN[9]?.componentes?.join(' - ')}`,
  LEARN_5_AB: `${LIBRO_LEARN[10].nombre} - ${LIBRO_LEARN[10].nivel} - ${LIBRO_LEARN[10]?.componentes?.join(' - ')}`,
  LEARN_6_CB: `${LIBRO_LEARN[11].nombre} - ${LIBRO_LEARN[11].nivel} - ${LIBRO_LEARN[11]?.componentes?.join(' - ')}`,
  LEARN_6_AB: `${LIBRO_LEARN[12].nombre} - ${LIBRO_LEARN[12].nivel} - ${LIBRO_LEARN[12]?.componentes?.join(' - ')}`,
  
  LEARN_NOW_1_CB: `${LIBRO_LEARN_NOW[0].nombre} - ${LIBRO_LEARN_NOW[0].nivel} - ${LIBRO_LEARN_NOW[0]?.componentes?.join(' - ')}`,
  LEARN_NOW_1_AB: `${LIBRO_LEARN_NOW[1].nombre} - ${LIBRO_LEARN_NOW[1].nivel} - ${LIBRO_LEARN_NOW[1]?.componentes?.join(' - ')}`,
  LEARN_NOW_2_CB: `${LIBRO_LEARN_NOW[2].nombre} - ${LIBRO_LEARN_NOW[2].nivel} - ${LIBRO_LEARN_NOW[2]?.componentes?.join(' - ')}`,
  LEARN_NOW_2_AB: `${LIBRO_LEARN_NOW[3].nombre} - ${LIBRO_LEARN_NOW[3].nivel} - ${LIBRO_LEARN_NOW[3]?.componentes?.join(' - ')}`,
  LEARN_NOW_3_CB: `${LIBRO_LEARN_NOW[4].nombre} - ${LIBRO_LEARN_NOW[4].nivel} - ${LIBRO_LEARN_NOW[4]?.componentes?.join(' - ')}`,
  LEARN_NOW_3_AB: `${LIBRO_LEARN_NOW[5].nombre} - ${LIBRO_LEARN_NOW[5].nivel} - ${LIBRO_LEARN_NOW[5]?.componentes?.join(' - ')}`,
  LEARN_NOW_4_CB: `${LIBRO_LEARN_NOW[6].nombre} - ${LIBRO_LEARN_NOW[6].nivel} - ${LIBRO_LEARN_NOW[6]?.componentes?.join(' - ')}`,
  LEARN_NOW_4_AB: `${LIBRO_LEARN_NOW[7].nombre} - ${LIBRO_LEARN_NOW[7].nivel} - ${LIBRO_LEARN_NOW[7]?.componentes?.join(' - ')}`,
  LEARN_NOW_5_CB: `${LIBRO_LEARN_NOW[8].nombre} - ${LIBRO_LEARN_NOW[8].nivel} - ${LIBRO_LEARN_NOW[8]?.componentes?.join(' - ')}`,
  LEARN_NOW_5_AB: `${LIBRO_LEARN_NOW[9].nombre} - ${LIBRO_LEARN_NOW[9].nivel} - ${LIBRO_LEARN_NOW[9]?.componentes?.join(' - ')}`,
  LEARN_NOW_6_CB: `${LIBRO_LEARN_NOW[10].nombre} - ${LIBRO_LEARN_NOW[10].nivel} - ${LIBRO_LEARN_NOW[10]?.componentes?.join(' - ')}`,
  LEARN_NOW_6_AB: `${LIBRO_LEARN_NOW[11].nombre} - ${LIBRO_LEARN_NOW[11].nivel} - ${LIBRO_LEARN_NOW[11]?.componentes?.join(' - ')}`,
  
  BRIGHT_STARTER_CB: `${LIBRO_BRIGHT[0].nombre} - ${LIBRO_BRIGHT[0].nivel} - ${LIBRO_BRIGHT[0]?.componentes?.join(' - ')}`,
  BRIGHT_STARTER_AB: `${LIBRO_BRIGHT[1].nombre} - ${LIBRO_BRIGHT[1].nivel} - ${LIBRO_BRIGHT[1]?.componentes?.join(' - ')}`,
  BRIGHT_1_CB: `${LIBRO_BRIGHT[2].nombre} - ${LIBRO_BRIGHT[2].nivel} - ${LIBRO_BRIGHT[2]?.componentes?.join(' - ')}`,
  BRIGHT_1_AB: `${LIBRO_BRIGHT[3].nombre} - ${LIBRO_BRIGHT[3].nivel} - ${LIBRO_BRIGHT[3]?.componentes?.join(' - ')}`,
  BRIGHT_2_CB: `${LIBRO_BRIGHT[4].nombre} - ${LIBRO_BRIGHT[4].nivel} - ${LIBRO_BRIGHT[4]?.componentes?.join(' - ')}`,
  BRIGHT_2_AB: `${LIBRO_BRIGHT[5].nombre} - ${LIBRO_BRIGHT[5].nivel} - ${LIBRO_BRIGHT[5]?.componentes?.join(' - ')}`,
  BRIGHT_3_CB: `${LIBRO_BRIGHT[6].nombre} - ${LIBRO_BRIGHT[6].nivel} - ${LIBRO_BRIGHT[6]?.componentes?.join(' - ')}`,
  BRIGHT_3_AB: `${LIBRO_BRIGHT[7].nombre} - ${LIBRO_BRIGHT[7].nivel} - ${LIBRO_BRIGHT[7]?.componentes?.join(' - ')}`,
  BRIGHT_4_CB: `${LIBRO_BRIGHT[8].nombre} - ${LIBRO_BRIGHT[8].nivel} - ${LIBRO_BRIGHT[8]?.componentes?.join(' - ')}`,
  BRIGHT_4_AB: `${LIBRO_BRIGHT[9].nombre} - ${LIBRO_BRIGHT[9].nivel} - ${LIBRO_BRIGHT[9]?.componentes?.join(' - ')}`,
  BRIGHT_5_CB: `${LIBRO_BRIGHT[10].nombre} - ${LIBRO_BRIGHT[10].nivel} - ${LIBRO_BRIGHT[10]?.componentes?.join(' - ')}`,
  BRIGHT_5_AB: `${LIBRO_BRIGHT[11].nombre} - ${LIBRO_BRIGHT[11].nivel} - ${LIBRO_BRIGHT[11]?.componentes?.join(' - ')}`,
  BRIGHT_6_CB: `${LIBRO_BRIGHT[12].nombre} - ${LIBRO_BRIGHT[12].nivel} - ${LIBRO_BRIGHT[12]?.componentes?.join(' - ')}`,
  BRIGHT_6_AB: `${LIBRO_BRIGHT[13].nombre} - ${LIBRO_BRIGHT[13].nivel} - ${LIBRO_BRIGHT[13]?.componentes?.join(' - ')}`,

  BRIGHTER_STARTER_CB: `${LIBRO_BRIGHTER[0].nombre} - ${LIBRO_BRIGHTER[0].nivel} - ${LIBRO_BRIGHTER[0]?.componentes?.join(' - ')}`,
  BRIGHTER_STARTER_AB: `${LIBRO_BRIGHTER[1].nombre} - ${LIBRO_BRIGHTER[1].nivel} - ${LIBRO_BRIGHTER[1]?.componentes?.join(' - ')}`,
  BRIGHTER_1_CB: `${LIBRO_BRIGHTER[2].nombre} - ${LIBRO_BRIGHTER[2].nivel} - ${LIBRO_BRIGHTER[2]?.componentes?.join(' - ')}`,
  BRIGHTER_1_AB: `${LIBRO_BRIGHTER[3].nombre} - ${LIBRO_BRIGHTER[3].nivel} - ${LIBRO_BRIGHTER[3]?.componentes?.join(' - ')}`,
  BRIGHTER_2_CB: `${LIBRO_BRIGHTER[4].nombre} - ${LIBRO_BRIGHTER[4].nivel} - ${LIBRO_BRIGHTER[4]?.componentes?.join(' - ')}`,
  BRIGHTER_2_AB: `${LIBRO_BRIGHTER[5].nombre} - ${LIBRO_BRIGHTER[5].nivel} - ${LIBRO_BRIGHTER[5]?.componentes?.join(' - ')}`,
  BRIGHTER_3_CB: `${LIBRO_BRIGHTER[6].nombre} - ${LIBRO_BRIGHTER[6].nivel} - ${LIBRO_BRIGHTER[6]?.componentes?.join(' - ')}`,
  BRIGHTER_3_AB: `${LIBRO_BRIGHTER[7].nombre} - ${LIBRO_BRIGHTER[7].nivel} - ${LIBRO_BRIGHTER[7]?.componentes?.join(' - ')}`,
  BRIGHTER_4_CB: `${LIBRO_BRIGHTER[8].nombre} - ${LIBRO_BRIGHTER[8].nivel} - ${LIBRO_BRIGHTER[8]?.componentes?.join(' - ')}`,
  BRIGHTER_4_AB: `${LIBRO_BRIGHTER[9].nombre} - ${LIBRO_BRIGHTER[9].nivel} - ${LIBRO_BRIGHTER[9]?.componentes?.join(' - ')}`,
  BRIGHTER_5_CB: `${LIBRO_BRIGHTER[10].nombre} - ${LIBRO_BRIGHTER[10].nivel} - ${LIBRO_BRIGHTER[10]?.componentes?.join(' - ')}`,
  BRIGHTER_5_AB: `${LIBRO_BRIGHTER[11].nombre} - ${LIBRO_BRIGHTER[11].nivel} - ${LIBRO_BRIGHTER[11]?.componentes?.join(' - ')}`,
  BRIGHTER_6_CB: `${LIBRO_BRIGHTER[12].nombre} - ${LIBRO_BRIGHTER[12].nivel} - ${LIBRO_BRIGHTER[12]?.componentes?.join(' - ')}`,
  BRIGHTER_6_AB: `${LIBRO_BRIGHTER[13].nombre} - ${LIBRO_BRIGHTER[13].nivel} - ${LIBRO_BRIGHTER[13]?.componentes?.join(' - ')}`,

} as const;